### ISSUE TITLE
[DISCUSSION] Can I Implement This Into One of My Projects?

### ISSUE THREAD

**Issue by XboxOneSogie720** [haiyuidesu/iBoot64Patcher#3]
Hi! I'm making a project that plays a video on an iPhone's screen before it boots into iOS. It's not a standalone thing, and only works if you have a computer, but I need to patch iBoot. Tihmstar and Cryptic's iBoot64Patcher are written in C++ and use Tihmstar's own library which is causing me lots of trouble. I noticed you've made a standalone version and was wondering if I can just implement this into my own?

Here's the layout I plan to use:

- iBoot64Patcher will be in a "3rdparty" folder along with some other projects that I will be using. That folder can either contain just the .c file and the LICENSE, or an entire archive of the repository. If you give me permission to use your iBoot64Patcher, let me know if you have any specific requests other than just having your .c file along with the LICENSE in my 3rdparty folder and being a part of my credits list.
Thanks!

**Comment by haiyuidesu** [comment]
Hello,

I'm fine with my project being a part of yours, if the LICENSE and credits are truly respected then I don't see any matters with it.

I hope your project will be achieved soon :')

**Comment by XboxOneSogie720** [comment]
Thanks! I'll be sure to include them.
