### ISSUE TITLE
[Bug] Auto restart after loading iBSS iOS 15.8 (19H370)

### ISSUE THREAD

**Issue by mast3rz3ro** [haiyuidesu/iBoot64Patcher#4]
Hi,

The bug exists in tihmstar's and dayt0n's patchers, I have issued here because your last commit was before just few hours.

I'm using img4lib for packing/decrypting and gaster to pwn

```
Product Name: iPhone8,2
iOS: iOS 15.8 (19H370)
```

```
$ ./iBoot64Patcher -p iBSS.dec iBSS.patched
[main]: starting...
[main]: detected iBoot-7459.140.15!
[main]: base_addr = 0x180380000
[main]: applying generic iBoot patches...

[rmv_signature_check]: removing signatures checks...
[rmv_signature_check]: found '_image4_validate_property_cb_interposer' beginning!
[rmv_signature_check]: patched to MOVZ x0, #0 insn = 0x18038d4b4
[rmv_signature_check]: patched to RET insn = 0x18038d4b8
[rmv_signature_check]: successfully removed signatures checks!

[main]: writing iBSS.patched...
[main]: done!
```

The extra switch seems not to work or maybe it's can be only applied for iBEC files ?
```
$ ./iBoot64Patcher -p iBSS.dec iBSS.patched -e
[main]: starting...
[main]: detected iBoot-7459.140.15!
[main]: base_addr = 0x180380000
[main]: applying generic iBoot patches...

[rmv_signature_check]: removing signatures checks...
[rmv_signature_check]: found '_image4_validate_property_cb_interposer' beginning!
[rmv_signature_check]: patched to MOVZ x0, #0 insn = 0x18038d4b4
[rmv_signature_check]: patched to RET insn = 0x18038d4b8
[rmv_signature_check]: successfully removed signatures checks!

[main]: writing iBSS.patched...
[main]: done!
```

I'll be waiting for your updates,
thanks you!

**Comment by haiyuidesu** [comment]
Hello,

Thank you for reporting your issue, `iBSS` image is a minimal version of the `iBoot` and consequently, it won't have the same capabilities than an `iBEC` image so what you are seeing here is the correct output.

You can read more about the `iBSS` [here](https://theapplewiki.com/wiki/IBSS), but if you want to apply the extra patches then you have to use an `iBEC`.

If you have more questions then I can answer them, if not then I would let you close the issue :')

**Comment by mast3rz3ro** [comment]
Actually I'm trying to boot an SSH ramdisk but after I load the patched 'iBSS' the device gets automatically rebooted, so I can not continue loading other ramdisk files (e.g `iBEC`) so I'm wondering if this issue is from the patcher maybe it's does not support this specific iOS version because it's been released early?

Waiting for your updates
Thank you!

**Comment by haiyuidesu** [comment]
I never booted an SSH Ramdisk before so I don't think I would be very suited to answer to this problem, I'm sorry-

However, about the `iBSS`, did you repack it as an `IMG4` file? (if not, maybe that could be the issue there)

In the doubt, here's my way of loading a patched image to a device:

```
iBoot64Patcher -p <component.dec> <component.pwn> [optionals arguments]

# make sure to use tihmstar img4tool (example with an actual `iBEC` image)
img4tool -c iBEC.im4p -t ibec -d ibec iBEC.pwn
img4tool -p iBEC.im4p -c iBEC.img4

irecovery -f iBEC.img4
```

If your issue still persists even with that then I couldn't tell what's the deal without any more context...

I hope it will help you :')
